### ISSUE TITLE
Getting ENOBUFS error when trying to fetch more number of secrets.

### ISSUE THREAD

**Issue by Gizmeondevwip** [jwerre/secrets#14]
I am getting error - 

```
{
  error: Error: spawnSync node ENOBUFS
      at Object.spawnSync (internal/child_process.js:1067:20)
      at spawnSync (child_process.js:602:24)
      at Secrets.getSecretSync (/home/ubuntu/test_api/node_modules/@jwerre/secrets/lib/secrets.js:220:16)
      at Object.module.exports.secretSync (/home/ubuntu/test_api/node_modules/@jwerre/secrets/index.js:30:23)
      at Object.<anonymous> (/home/ubuntu/test_api/routes/globals.js:9:44)
      at Module._compile (internal/modules/cjs/loader.js:1063:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
      at Module.load (internal/modules/cjs/loader.js:928:32)
      at Function.Module._load (internal/modules/cjs/loader.js:769:14)
      at Module.require (internal/modules/cjs/loader.js:952:19)
      at require (internal/modules/cjs/helpers.js:88:18)
      at Object.<anonymous> (/home/ubuntu/test_api/routes/initial.js:4:5)
      at Module._compile (internal/modules/cjs/loader.js:1063:30)
      at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
      at Module.load (internal/modules/cjs/loader.js:928:32)
      at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
    errno: -105,
    code: 'ENOBUFS',
    syscall: 'spawnSync node',
    path: 'node',
    spawnargs: [
      '/home/ubuntu/test_api/node_modules/@jwerre/secrets/lib/readline'
    ]
  },
  status: null,
  signal: 'SIGTERM',
  output: [
    null,
    <Buffer 7b 22 63 6f 6e 66 69 67 22 3a 22 7b 5c 22 53 48 4f 50 49 46 59 5f 53 54 4f 52 45 5f 46 52 4f 4e 54 5f 41 43 43 45 53 53 5f 54 4f 4b 45 4e 5c 22 3a 5c ... 65486 more bytes>,
    <Buffer >
  ],
  pid: 24306,
  stdout: <Buffer 7b 22 63 6f 6e 66 69 67 22 3a 22 7b 5c 22 53 48 4f 50 49 46 59 5f 53 54 4f 52 45 5f 46 52 4f 4e 54 5f 41 43 43 45 53 53 5f 54 4f 4b 45 4e 5c 22 3a 5c ... 65486 more bytes>,
  stderr: <Buffer >
}
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Secrets.getSecretSync (/home/ubuntu/test_api/node_modules/@jwerre/secrets/lib/secrets.js:225:18)
    at Object.module.exports.secretSync (/home/ubuntu/test_api/node_modules/@jwerre/secrets/index.js:30:23)
    at Object.<anonymous> (/home/ubuntu/test_api/routes/globals.js:9:44)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/ubuntu/test_api/routes/initial.js:4:5)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

It is working fine when I removed a particular key, is there any limit in buffer returned?

**Comment by Gizmeondevwip** [comment]
When I edited this file and changed the buffer to 1 MB, it is working fine. Is there any way to pass this as an argument instead of editing in node_modules?

**Comment by jwerre** [comment]
@Gizmeondevwip there is a pull request which adds a maxBuffer options. I'll take a look at this today and merge.

**Comment by jwerre** [comment]
Added maxBuffer argument to version 2.0.4
